### ISSUE TITLE
DataTable > Column: support custom components as Column renderers

### ISSUE THREAD

**Issue by reksc** [primefaces/primevue#3755] opened 2023-03-16 14:44 UTC
### Describe the feature you would like to see added

I think this is related to this issue from PrimeReact: https://github.com/primefaces/primereact/issues/2268.

I'd really like to refactor some of my table definitions and have repetitive Columns definitions in external SFC's. E.g. `PriorityStatusColumn`.

However, if I use any other component than `Column` in `DataTable`'s default slot, then it gets ignored (without errors).

I think this is the part od `DataTable.vue` code responsible for the above:

```js
if (children && children.length) {
    children.forEach((child) => {
        if (child.children instanceof Array) {
            results.concat(this.recursiveGetChildren(child.children, results));
        } else if (child.type.name == 'Column') {
            results.push(child);
        }
    });
}
```

It's common to extract columns into components, AgGrid has this and many other as well.

### Is your feature request related to a problem?

I'm always frustrated when ... _I copy and paste the same definitions for Columns inside different views_

**Comment by Voltra** [comment] 2023-03-17 18:38
Yes please! Although I'm curious of the impact of the current proposed solution to nested tables (like having one in a modal for instance)

**Comment by gnucifer** [comment] 2023-07-12 14:35
Yes! I have ran into the exact same issue. My current workaround is creating a composable:

```javascript
const { userColumnAttributes, multiSelectAttributes } = UseUserColumn({ filters })
```

but this still leaves you with some remaining boiler plate code and end up feeling like a bit like a hack:

```html
<Column header="Updated by" v-bind="userColumnAttributes">
  <template #filter="{filterModel, filterCallback}">
    <MultiSelect
       v-model="filterModel.value"
       @change="filterCallback()"
       v-bind="multiSelectAttributes"
    />
  </template>
</Column>
```

**Comment by Voltra** [comment] 2023-07-12 16:09
I've used a similar approach in my workaround for Vue 2 with Primevue 2, using mixins and functions where appropriate.

**Comment by jkocyigi** [comment] 2023-07-18 11:13
+1

**Comment by NikoGJ** [comment] 2023-08-27 17:41
Also had the same requirement. That would be a nice improvement to the library.

**Comment by Quang-Dong** [comment] 2023-11-28 08:40
+1

**Comment by santhikumar43** [comment] 2023-12-20 05:01
+1

**Comment by mertsincan** [comment] 2023-12-20 10:54
Duplicate of https://github.com/primefaces/primevue/issues/4646

**Closed by mertsincan** 2023-12-20 10:54 UTC
Labels: Status: Discussion, Type: New Feature

**Comment by cybearz** [comment] 2024-05-15 13:28
+1

**Comment by japentaca** [comment] 2024-08-10 21:22
+1

**Comment by petr-hybler-ofti** [comment] 2024-10-07 15:01
+1
