### ISSUE TITLE
Primevue v4 memory leak problem

### ISSUE THREAD

**Issue by RoyeL12** [primefaces/primevue#5960] opened 2024-06-24 19:31 UTC
### Describe the bug

Hi there, i just want to let you know there is a memory leak problem server side with primevue v4 for nuxt. Not sure exactly what is causing it but i know it is v4 because the leak disspeared when i downgraded back to v3.56
![image](https://github.com/primefaces/primevue/assets/96084338/5fa56733-3f88-4f44-bca8-574db9597af5)

### Reproducer

https://stackblitz.com

### PrimeVue version

4.0.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Nuxt

### Browser(s)

all

### Steps to reproduce the behavior

upgrade to v4 on nuxt

**Comment by mertsincan** [comment] 2024-06-24 21:25
Hi @RoyeL12,

Thanks a lot for your screenshot! Could you please create a sample project for us to replicate? Thank you.

**Comment by luke-z** [comment] 2024-06-25 06:15
might be related to my issue #5957

**Comment by mertsincan** [comment] 2024-06-25 08:38
Duplicate of https://github.com/primefaces/primevue/issues/5957

**Closed by mertsincan** 2024-06-25 08:38 UTC
Labels: Resolution: Duplicate
