### ISSUE TITLE
Quill Editor V2.0.1 support

### ISSUE THREAD

**Issue by CodeCube0** [primefaces/primevue#5720] opened 2024-05-10 10:35 UTC
### Describe the bug

The "quill" editor at version 2.0.1 does not support primevue. The v-model part, if set, does not pre-value any value

### Reproducer

https://stackblitz.com/edit/3npuga?file=package.json,src%2FApp.vue

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome 124.0.6367.202

### Steps to reproduce the behavior

In the example proposed in the documentation [https://primevue.org/editor/#basic](url)
I tried to run the example on stackblitz, as reported in the documentation and you use version 1.3.7 and for security reasons "quill" has been updated to 2.0.1.
it would be appreciated to specify the version of quill to use or introduce support for the new version 2.0.1 and beyond

**Comment by yushanfans2233** [comment] 2024-07-17 08:40
Hey @CodeCube0 , I'd like to pick up this issue, but it might need to make a lot of changes to upgrade Quill to 2.x, can I do it in a single PR? Or do you have any idea on how to chunk it into small pieces?

**Comment by ineshbose** [comment] 2024-08-30 19:53
Is this issue duplicate of https://github.com/primefaces/primevue/issues/5606? https://github.com/primefaces/primevue/issues/5606#issuecomment-2206793034 worked for me in the provided Stackblitz link.

**Closed** 2024-12-02 15:02 UTC
Labels: Status: Needs Triage
