### ISSUE TITLE
InputNumber: Doubling digitals in currency mode

### ISSUE THREAD

**Issue by MikeLacroix** [primefaces/primevue#3580] opened 2023-01-24 09:20 UTC
### Describe the bug

This bug can be seen also in an offical documentation in [https://www.primefaces.org/primevue/inputnumber](https://www.primefaces.org/primevue/inputnumber) > Currency > Japan.

Everything works well when user fills in a value with length smaller then 4 (eg. "123"). When I try to fill longer-length value (eg. "1234") last digits are doubled. It means instead of 1234 I will automatically receive 12344. When I type 12345 I receive 1234455 and so on.

### Reproducer

https://www.primefaces.org/primevue/inputnumber

### PrimeVue version

3.22.3

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

**Comment by Slayvin** [comment] 2023-07-19 09:01
Seems to be fixed with #3999

**Comment by tugcekucukoglu** [comment] 2023-10-30 10:57
Please try to use with the latest version. If the problem still persists, please create a new issue with a reproducer link.

**Closed by tugcekucukoglu** 2023-10-30 10:57 UTC
Labels: Status: Needs Triage

**Comment by MikeLacroix** [comment] 2023-10-30 11:17
Seems okay now, thanks.
