### ISSUE TITLE
The update:model-value event in the InputNumber component isn't working as expected. It only triggers on blur or when pressing Enter, instead of triggering when the value changes.

### ISSUE THREAD

**Issue by ruanpasta** [primefaces/primevue#6241] opened 2024-08-16 14:32 UTC
### Describe the bug

The _update:model-value_ event in the _InputNumber_ component isn't working as expected. It only triggers on blur or when pressing Enter, instead of triggering when the value changes.

When we press TAB the _update:model-value_ is triggered two times.
If we press Enter the _update:model-value_ is triggered too.

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-6gf5np?file=src%2FApp.vue

### PrimeVue version

4.0.4

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Brave/Edge

### Steps to reproduce the behavior

Import  and use the InputNumber and try to use the _update:model-value_ event.

### Expected behavior

Like the other inputs, I believe the expected behavior is for the update event to trigger each time the input value changes.

**Comment by tugcekucukoglu** [comment] 2024-08-16 20:10
Reference issue: https://github.com/primefaces/primevue/issues/506

Closing because it is not a bug.

**Closed by tugcekucukoglu** 2024-08-16 20:10 UTC
Labels: Status: Needs Triage
