### ISSUE TITLE
Disabled options do not get disabled

### ISSUE THREAD

**Issue by makurtu** [primefaces/primevue#1192] opened 2021-04-19 10:12 UTC
I think that `Dropdown` should have an attribute that allows you to mark certain item as disabled.

There is already and `optionDisabled`, but its only a boolean, and you can`t conditionate an item.

An example:

```js
<Dropdown v-model="selectedAdult" :options="adults" optionLabel="name" placeholder="Select an Adult" />
```

and you have:

```js
data() {
	return {
		selectedAdult: null,
		adults: [
			{name: 'Alice', age: 20},
			{name: 'Bob', age: 16},
			{name: 'Ducke', age: 22},
			{name: 'Michael', age: 35},
			{name: 'Tommy', age: 12}
		]
	}
}
```

How can I set _Bob_ and _Tommy_ as disabled? I can't interact with item's `age` .

**Comment by codenomnom** [comment] 2021-04-22 07:56
There's a history here: https://github.com/primefaces/primevue/issues/1037 which is "fixed" by https://github.com/primefaces/primevue/commit/342f251212f309d3074ea048859ebe35fd4d8eb3 .

Unfortunately it completely breaks the functionality, even though you can still achieve it. Currently you can disable single item like that:

```html
<Dropdown optionDisabled="anything" />
```
```javascript
options = [{
  // ... item properties
  optionDisabled: true
}]
```

This is because the current code is this:
```javascript
isOptionDisabled(option) {
    return this.optionDisabled ? option.optionDisabled : false;
},
```

As you can see, it checks for the **component property** `optionDisabled`, and if it has *any* truthy value, then it sets disabled to the **option's** property `optionDisabled`. They are two completely different things, and the second **must** be a boolean.

The previous code was:
```javascript
return this.optionDisabled ? ObjectUtils.resolveFieldData(option, this.optionDisabled) : false;
```

I am not completely sure why this was marked as broken. I was able to properly use it before like that:
```html
<Dropdown optionDisabled="myDisabledPropertyKey" />
```
```javascript
options = [{
  // ... item properties
  myDisabledPropertyKey: true
}]
```
And it worked like a charm. Exactly like how `optionLabel` and `optionValue` work.

@tugcekucukoglu do you have any memory of what made you do this change?

**Comment by makurtu** [comment] 2021-04-22 08:50
First of all, many thanks @codenomnom for your time!

The implementation seems nice, but I think that's not the best way to solve it, because my data comes from an API, so with this implementation, I can't use directly the code from API, I have to edit it by setting this `myDisabledPropertyKey` to true.

Anyway, I will give it a try :+1:

**Comment by cagataycivici** [comment] 2021-05-12 12:18
Seems to be a regression, fixed now. Thank you.

**Closed** 2021-05-12 12:17 UTC
Labels: bug, priority - high
