### ISSUE TITLE
TabView does not support dynamic tabs

### ISSUE THREAD

**Issue by MelihAltintas** [primefaces/primevue#616] opened 2020-11-01 22:02 UTC
The versions I am using:  "primevue": "3.0.1", "vue": "3.0.0",

Example
![T4wdR](https://user-images.githubusercontent.com/9059535/97816542-0c839c00-1ca7-11eb-9481-30e3a7fd25ac.png)
Result:
![zjHec](https://user-images.githubusercontent.com/9059535/97816551-186f5e00-1ca7-11eb-9e40-332adb7add56.png)

or

```
    <Accordion >
        <AccordionTab header="Header I">
            Content
        </AccordionTab>
        <AccordionTab :header="header" v-for="header in ['a','b','c','d']" :key="header">
            header
        </AccordionTab>
        <AccordionTab header="Header III">
            Content
        </AccordionTab>
    </Accordion>
```

![Untitled](https://user-images.githubusercontent.com/9059535/97816736-3b4e4200-1ca8-11eb-9256-03e51f0c5534.png)

**Comment by cagataycivici** [comment] 2020-11-25 12:49
Duplicate of https://github.com/primefaces/primevue/issues/622

**Comment by cagataycivici** [comment] 2020-11-25 13:00
Oh, this is for TabView, reopening.

**Comment by cagataycivici** [comment] 2020-11-25 13:17
Resolved and added a demo

**Closed by cagataycivici** 2020-11-25 13:17 UTC
Labels: bug
