### ISSUE TITLE
Add reset page on filter property to Table

### ISSUE THREAD

**Issue by shaan1974** [primefaces/primevue#1129] opened 2021-03-28 14:10 UTC
Hello, 

Is it possbile to define an option (true,false) to the fact that when a filter is taken in count we don't go on first page automatically ( I reffer to Fixed #928 )

I explain, i'm on lazy loading, and i want to run the filter(s) only when a button (apply filters ) is press.
And when this button gonna press, the lazy loading refresh data and goes on page one.

Thanks

**Comment by cagataycivici** [comment] 2021-08-19 10:34
This is by design and we did not have many feedback on this in other Prime libraries as well, due to lack of interest closing. If there is more demand, we'll reopen and implement it.

**Closed by cagataycivici** 2021-08-19 10:34 UTC
