### ISSUE TITLE
Theme: lara-light-green/theme.css got Warning on Primevue 3.47.2

### ISSUE THREAD

**Issue by MEngMAHCelebi** [primefaces/primevue#5162] opened 2024-01-28 14:18 UTC
### Describe the bug

Got Warning with Primevue 3.47.2 on Theme but not with 3.46.0
See below pictures:

<img width="643" alt="Bildschirmfoto 2024-01-28 um 17 14 15" src="https://github.com/primefaces/primevue/assets/79258865/0c3c74c0-83f4-4d7b-8373-b70829fba4b4">

<img width="643" alt="Bildschirmfoto 2024-01-28 um 17 13 34" src="https://github.com/primefaces/primevue/assets/79258865/cd6f8eca-8e76-4a53-a52c-7dfb42b21eba">

### Reproducer

can-not-shpw

### PrimeVue version

3.47.2

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by mertsincan** [comment] 2024-01-28 23:27
Duplicate of https://github.com/primefaces/primevue/issues/5155

**Closed by mertsincan** 2024-01-28 23:27 UTC
Labels: Status: Needs Triage

**Comment by MEngMAHCelebi** [comment] 2024-01-28 23:31
sry, i searched for it, but don't find if its already postet.
