### ISSUE TITLE
Datatable - dynamic column - vue 3.1.1

### ISSUE THREAD

**Issue by welcome14** [primefaces/primevue#1327] opened 2021-06-08 16:54 UTC
I have update Vue by 3.0.5 to 3.1.1 and the dynamic column not show. 
I don't have error in console or other warning log.

I had to go back to 3.0.5.

**Comment by tugcekucukoglu** [comment] 2021-06-09 06:52
Duplicate of [#1323](https://github.com/primefaces/primevue/issues/1323)

**Closed by tugcekucukoglu** 2021-06-09 06:52 UTC
