### ISSUE TITLE
Select/MultiSelect: onOverlayLeave should not try and focus on Filter

### ISSUE THREAD

**Issue by 1Map** [primefaces/primevue#6564] opened 2024-10-12 10:38 UTC
### Describe the bug

The following line in your code throws an error as filterInput is null:

focus(this.$refs.filterInput.$el);

https://github.com/primefaces/primevue/blob/22d6f8a03724f30b6695a0800412f77a3a8ed738/packages/primevue/src/select/Select.vue#L710

I do not think it should try and focus on the filter during onOverlayLeave as the filterInput is not always there (null)

### Reproducer

N/A

### PrimeVue version

Latest

### Vue version

4.x

### Language

ALL

### Build / Runtime

Vite

**Comment by CCodam** [comment] 2024-10-12 10:57
Duplicate of #6539 and #6545

**Comment by tugcekucukoglu** [comment] 2024-11-12 06:34
Duplicate

**Closed by tugcekucukoglu** 2024-11-12 06:34 UTC
Labels: Status: Needs Triage
