### ISSUE TITLE
Password: input value always have one character

### ISSUE THREAD

**Issue by mateenagy** [primefaces/primevue#5589] opened 2024-04-15 20:59 UTC
### Describe the bug

When I start typing in the input field always the last character remaining in the input.

### Reproducer

https://stackblitz.com/edit/ukbwvi?file=src%2FApp.vue

### PrimeVue version

3.50.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome, Safari

### Steps to reproduce the behavior

Click in the input -> Start typing

### Expected behavior

Have more then one character in the input

**Comment by ArtemDehteruk** [comment] 2024-04-17 06:23
Hello.
The problem is fixed in the Vue 3.4.23 version.
Thanks.

**Closed** 2024-04-17 21:19 UTC
Labels: Status: Needs Triage
