### ISSUE TITLE
Dropdown menu has a little lag

### ISSUE THREAD

**Issue by hurahurat** [primefaces/primevue#1458] opened 2021-08-19 14:11 UTC
Hi, I'm using primevue Dropdown and finding it has a little lag when selecting an item in the dropdown menu.
**Current behavior**
 - It takes about 0.2s to make the dropdown menu be hidden.

**Expected behavior**
- Dropdown menu should be disappeared immediately when selecting an item.

**Comment by tugcekucukoglu** [comment] 2021-08-23 09:16
It's expected behavior, kind of a closing animation.

**Closed by tugcekucukoglu** 2021-08-23 09:16 UTC

**Comment by wsaca** [comment] 2021-11-08 16:24
@tugcekucukoglu This [200ms delay](https://github.com/primefaces/primevue/blob/e78feb914a0f6a647c1b5412701eba56a4781451/src/components/dropdown/Dropdown.vue#L430) is annoying because it's added to the transition time. It makes feel the app very slow when we have a lot of dropdown components.

This delay is not applied when we use the keyboard, what's the reason for having a different behavior if `ripple` is disabled?

**Comment by rubjo** [comment] 2021-11-09 07:37
@tugcekucukoglu I agree with the OP, you should consider dropping the delay if `ripple` is disabled to avoid the component appearing slow and laggy.
