### ISSUE TITLE
Dropdown Type Error

### ISSUE THREAD

**Issue by ajon88** [primefaces/primevue#2861] opened 2022-08-17 05:35 UTC
### Describe the bug

- error TS2322: Type '{ modelValue: any; options: { name: string; code: string; }[]; optionLabel: string; optionValue: string; placeholder: string; }' is not assignable to type 'IntrinsicAttributes & DropdownProps & VNodeProps & AllowedComponentProps & ComponentCustomProps'.
  Type '{ modelValue: any; options: { name: string; code: string; }[]; optionLabel: string; optionValue: string; placeholder: string; }' is missing the following properties from type 'DropdownProps': align, addEventListener, removeEventListener, accessKey, and 277 more.

### PrimeVue version

3.16.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Build with type check

### Expected behavior

no Error

**Comment by mertsincan** [comment] 2022-08-17 09:24
Duplicate of https://github.com/primefaces/primevue/issues/2845

**Closed by mertsincan** 2022-08-17 09:24 UTC
Labels: bug
