### ISSUE TITLE
Carousel: config aria.slideNumber undefined

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#3453] opened 2022-12-28 14:01 UTC
### Describe the bug

After updating from Primevue 3.20.0 to 3.21.0, I get this error:

**this.$primevue.config.locale.aria.slideNumber** is undefined
I dont have an aria.slideNumber config.
I checked the example-config at https://github.com/primefaces/primelocale.
There's also no slideNumber to be found.
I can add a slideNumber to my localconfig. That fixes the error. But I have no idea what value am I supposed to set there.
I would expect primevue to fallback to a default config and not throw an error.

![image](https://user-images.githubusercontent.com/8471027/209822664-90f4ce6e-0d13-4022-b6df-dae86517382e.png)

### Reproducer

version update

### PrimeVue version

3.21.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Expected behavior

I would expect primevue to fallback to a default config and not throw an error.

**Comment by bahadirsofuoglu** [comment] 2022-12-30 13:24
Hi, Could you share the value prop array you passed?

**Comment by Rakasch** [comment] 2022-12-30 14:17
with "value prop array" you mean my locale ?
`app.use(PrimeVue, {    locale: locales, ... } );`
where locales is:
```
 {
  startsWith: "Beginnt mit",
  contains: "Enthält",
  notContains: "Enthält nicht",
  endsWith: "Endet mit",
  equals: "Ist gleich",
  notEquals: "Ist nicht gleich",
  noFilter: "Kein Filter",
  lt: "Kleiner als",
  lte: "Kleiner gleich",
  gt: "Größer als",
  gte: "Größer gleich",
  dateIs: "Datum ist",
  dateIsNot: "Datum ist nicht",
  dateBefore: "Datum ist vor",
  dateAfter: "Date ist nach",
  clear: "Clear",
  apply: "Anwenden",
  matchAll: "Und-Verknüpft",
  matchAny: "Oder-Verknüpft",
  addRule: "Regel hinzufügen",
  removeRule: "Regel entfernen",
  accept: "Ja",
  reject: "Nein",
  choose: "Wähle",
  upload: "Upload",
  cancel: "Abbrechen",
  dayNames: ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"],
  dayNamesShort: ["Son", "Mon", "Die", "Mit", "Don", "Fre", "Sam"],
  dayNamesMin: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
  monthNames: [
    "Januar",
    "Februar",
    "März",
    "April",
    "Mai",
    "Juni",
    "Juli",
    "August",
    "September",
    "Oktober",
    "November",
    "Dezember",
  ],
  monthNamesShort: ["Jan", "Feb", "Mar", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"],
  today: "Heute",
  weekHeader: "KW",
  firstDayOfWeek: 1,
  dateFormat: "dd.mm.yy",
  weak: "schwach",
  medium: "mittel",
  strong: "stark",
  passwordPrompt: "Gebe ein Password ein",
  emptyFilterMessage: "Kein Ergebnis gefunden",
  emptyMessage: "Keine verfügbaren Optionen",
  aria: {
    trueLabel: "True",
    falseLabel: "False",
    nullLabel: "Not Selected",
    star: "1 Stern",
    stars: "{star} Sterne",
    selectAll: "Alle gewählt",
    unselectAll: "Keine gewählt",
    close: "Schließen",
    previous: "Previous",
    next: "Next",
  },
};
```

I have since added my missing locales from here:
https://www.primefaces.org/primevue/locale

The problem is that I get an error after an primevue update when primevue has added a new locale each time. Since I don't have the new locale in my config yet of course.
Here primevue should use the default value instead of throwing a cryptic error.

**Comment by bahadirsofuoglu** [comment] 2022-12-30 14:27
I think your files overwrite to default locale files. Could you try to add slideNumber: '{slideNumber}' to the aria object?
 '{slideNumber}' is a dynamic value using your value prop's index.

**Comment by Rakasch** [comment] 2022-12-30 14:48
I have since added my missing locales from here:
https://www.primefaces.org/primevue/locale

The problem is that **each time** primevue adds a new locale I get an error after updating. 
Since I don't have the new locale in my config yet of course.
Primevue should use a default value instead of throwing a cryptic error.

**Comment by bahadirsofuoglu** [comment] 2022-12-30 15:07
Did you try to spread the object?

**Comment by Rakasch** [comment] 2022-12-30 15:09
Can I somehow get the default locale object from primevue ?
Then I can overwrite only the values I want to change.

**Comment by bahadirsofuoglu** [comment] 2022-12-30 15:17
You have access to the default locale files via primevue.config.locale. You can make changes on it. I believe the solution is here. I think the problem is not related to the component. For this reason, I am closing the issue. I hope it helped.

**Closed by bahadirsofuoglu** 2022-12-30 15:17 UTC
Labels: Status: Discussion

**Comment by Rakasch** [comment] 2023-01-09 15:42
> You have access to the default locale files via primevue.config.locale. 

I dont understand how to access the PrimeVue locale when initializing the PrimeVue App.

`import PrimeVue from "primevue/config";`

What I would want to do to solve the issue is: make a copy from PrimeVue locales and modify it.
`const myLocales = {...PrimeVue.locale};`
But PrimeVue.locale does not exist ! 
How can I access the locale here?

And then pass it to the initialisation.
```
app.use(PrimeVue, {
    locale: myLocales,
```
