### ISSUE TITLE
InputNumber: digit duplication when using suffix prop

### ISSUE THREAD

**Issue by unjapones** [primefaces/primevue#3964] opened 2023-05-16 10:15 UTC
### Describe the bug

The input duplicates the last entered digit when the prop suffix is used.

### Reproducer

https://primevue.org/inputnumber/#prefixsuffix

### PrimeVue version

3.29.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome, Firefox, Safari

### Steps to reproduce the behavior

1. Go to the InputNumber/Prefix & Suffix demo/section page https://primevue.org/inputnumber/#prefixsuffix.
2. Focus the input under the "Mile" label (has the "mi" suffix).
3. Write 123...4
4. An extra 4 gets appended to the end of to the value string (and the same applies if you write "5")

### Expected behavior

5. No duplication of digits should happen.

![Screenshot 2023-05-16 at 12 13 32](https://github.com/primefaces/primevue/assets/4421917/e604eec6-9133-468a-8425-856e2db0bcd7)

**Comment by kukudim** [comment] 2023-05-30 10:52
Really need a fix.

**Comment by Slayvin** [comment] 2023-07-19 08:56
I had the same issue, but it seems to be fixed with version 3.30.1
Probably fixed with #3999

**Comment by dimitriadisg** [comment] 2023-10-03 08:13
Actually fixed in `3.30.0`, but still clunky with default value of 0

**Comment by tugcekucukoglu** [comment] 2023-10-30 11:17
Please try to use with the latest version. If the problem still persists, please create a new issue with a reproducer link.

**Closed by tugcekucukoglu** 2023-10-30 11:17 UTC
Labels: Status: Needs Triage
