### ISSUE TITLE
There is no possibility to add a text to "select all" action.

### ISSUE THREAD

**Issue by itapingu** [primefaces/primevue#2138] opened 2022-02-10 16:13 UTC
https://github.com/primefaces/primevue/blob/dd849da61ab7298a73b79382a27bb1b2c0e322e4/src/components/multiselect/MultiSelect.vue#L43

Here you are only allowing a filter to be added, but there is no option to do something easier like adding a text between the checkbox and the X.
In the scenario I'm encountering I need to add a simple text like "All countries" there, I think this can be easily achieve with a dedicated prop. 
Even better would be to add 2 props, one for each state of `allSelected`, something like:
- selectAllLabel => 'All countries'
- selectNoneLabel => ' No countries'

**Comment by rubjo** [comment] 2022-04-01 06:18
Duplicate of #481

**Closed** 2022-08-10 14:21 UTC
Labels: enhancement
