### ISSUE TITLE
AutoComplete: `aria-hidden="true"` on close chip console causes error

### ISSUE THREAD

**Issue by bobby-driggs** [primefaces/primevue#6141] opened 2024-07-29 19:21 UTC
### Describe the bug

Using the AutoComplete component, I noticed we have some aria errors. I also noticed this exists on the primevue website:

<img width="1002" alt="image" src="https://github.com/user-attachments/assets/1ca5b034-1ebe-484d-98f8-34ea73ec7de3">

### Reproducer

https://primevue.org/autocomplete/

### PrimeVue version

4.0.2

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Brave 1.68.131 (Chromium: 127.0.6533.73)

### Steps to reproduce the behavior

Use AutoComplete component w/ `multiple` option, and see console errors when selecting multiple items

### Expected behavior

No Aria errors

**Comment by Chrysochrome** [comment] 2024-07-31 06:35
I’ve encountered this issue frequently in the Menu component. Clicking on any menu item triggers this error in the console, including in ContextMenu, Dock, Menu, Menubar, etc. The problem also exists on the PrimeVue website.

Reproducer

https://primevue.org/menubar/

**Comment by tugcekucukoglu** [comment] 2024-08-02 09:45
![Screenshot 2024-08-02 at 12 43 46](https://github.com/user-attachments/assets/886acd75-6191-494a-a9fd-6b6194098730)

I cannot replicate the problem. Am I missing something? 
Extensions can cause these errors.

**Comment by hiddenyak** [comment] 2024-08-02 17:40
With no extensions enabled, I get this bug on the PrimeVue website, interacting with any menu component exactly like Chrysochrome describes, on both Chrome and Edge but not Firefox.

Chrome Version 127.0.6533.89 (Official Build) (64-bit)
Edge Version 127.0.2651.74 (Official Build) (64-bit)
Firefox 128.0.3

**Comment by GerGotha** [comment] 2024-08-05 13:15
I have had similar issues with the Menu components. Strangely enough, for me it only occured as soon as I selected any element with the devtools element picker and interacted with a menu after doing so.
Tried with Firefox, Chrome and Edge.

**Comment by Aspyryan** [comment] 2024-08-07 06:59
Can reproduce this as well on Edge (Version 127.0.2651.86). I also got this problem with primevue `3.52`

**Comment by eneeio-nm** [comment] 2024-08-09 09:22
I get the console error from Menu items:

![screenshot-2024-08-09--10 20 34@2x](https://github.com/user-attachments/assets/22db3700-1bdf-436f-88d4-7c7183268553)

From what I can tell is it's complaining about this example:

![screenshot-2024-08-09--10 21 47@2x](https://github.com/user-attachments/assets/4da8136c-c7ff-4161-8f30-6ffca81dafdf)

**Comment by eneeio-nm** [comment] 2024-08-09 09:30
I've created an example of this happening on [Stackblitz](https://stackblitz.com/edit/ui4cff?file=src%2FApp.vue), hopefully the issue can be fixed now.

**Comment by LanFeusT23** [comment] 2024-08-13 13:34
@tugcekucukoglu This seems to be a Chrome update, I've seen several other packages have that error now but it doesn't show on Firefox.

For example: https://github.com/ant-design/ant-design/issues/50170

**Comment by Coops0** [comment] 2024-08-15 18:05
A temporary fix I have found to work for myself
```ts
const vFixAriaBug = {
  mounted(el: HTMLElement) {
    el.ariaHidden = null;
  },
  updated(el: HTMLElement) {
    el.ariaHidden = null;
  }
};
```


Then usable by
```vue
<template>
  <Menubar v-fix-aria-bug>
    <template>
        <router-link ...>
          <a v-fix-aria-bug ...>
        </router-link>
    </template>
  </Menubar>
</template>
```

**Comment by peacefulseeker** [comment] 2024-08-18 16:10
For those, using primevue v3 `Menu`, as a temp fix, 
you can pass `pt` prop with `action`(itemLink in past) attribute override.

Source for menu item(with action `a` tag) https://github.com/primefaces/primevue/blob/v3/components/lib/menu/Menuitem.vue

```
const accountMenuItems = ref([
    {
      label: () => `label`,
      command: () => router.push({ name: 'route' }),
    },
 ...
]);

<Menu
  @focus="onFocus"
  @blur="onBlur"
  :model="accountMenuItems"
  :pt="{
    // fixes https://github.com/primefaces/primevue/issues/6141
    action: {
      ariaHidden: false,
    },
  }"
  :popup="true" />
```

At least, the warning has gone in Chrome 127+

**Comment by reiven93** [comment] 2024-08-20 13:02
If anyone is using SplitButton you can also PT the attr to the tiered menu item:

`<SplitButton class="ml-1" :model="itemsSubMenu"
                            :pt="{ pcMenu: { itemLink: { ariaHidden: false } } }">
                        </SplitButton>`

**Comment by tugcekucukoglu** [comment] 2024-08-21 09:45
Still cannot replicate AutoComplete issue. I could see that there is a problem with anchor tags. Please follow this issue for menus: https://github.com/primefaces/primevue/issues/6269

**Closed by tugcekucukoglu** 2024-08-21 09:45 UTC
Labels: Status: Needs Triage

**Comment by bonniegrubbs** [comment] 2024-08-27 17:50
To replicate, you can do this on the Primevue example [here](https://tailwind.primevue.org/menu/#router)
<img src="https://github.com/user-attachments/assets/96d270ab-d701-4956-990d-de28e7c111b7" width="600" />

**Comment by scottmillion** [comment] 2025-01-08 21:38
Had this issue on TieredMenu component. 

@mousedown.prevent fixed it.
