### ISSUE TITLE
DataTable: typescript has to be generic

### ISSUE THREAD

**Issue by Hulkmaster** [primefaces/primevue#3742] opened 2023-03-13 13:38 UTC
### Describe the feature you would like to see added

```
    /**
     * Callback to invoke when cell edit is completed.
     * @param {DataTableCellEditCompleteEvent} event - Custom cell edit complete event.
     */
    'cell-edit-complete'(event: DataTableCellEditCompleteEvent): void;
```
   
```
import PrmDataTable, {
  DataTableCellEditCompleteEvent,
} from 'primevue/datatable';
```

`DataTableCellEditCompleteEvent` should be generic and should accept (and emit initially) the type of object, which was used in 

```
  <prm-data-table
    :value="data"
    edit-mode="cell"
    @cell-edit-complete="onCellEdit"
  >
  ```
  
  Bad
  ```
  function onCellEdit(event: DataTableCellEditCompleteEvent) {
     (event.data as IMyType);
  }
  ```
  
  Good
  ```
  function onCellEdit(event: DataTableCellEditCompleteEvent<IMyType>) {}
  ```
  
  Perfect
  ```
  function onCellEdit(event: DataTableCellEditCompleteEvent) {
  // type of data object is already figured out by table component and is provided here
  }
  ```

**Comment by septatrix** [comment] 2023-05-27 15:32
This should be possible with the support for generics in Vue 3.3

**Comment by m3hari** [comment] 2023-10-16 15:22
related https://github.com/primefaces/primevue/issues/3995

**Comment by mertsincan** [comment] 2023-12-20 10:48
Duplicate of https://github.com/primefaces/primevue/issues/3995

**Closed by mertsincan** 2023-12-20 10:48 UTC
Labels: Status: Discussion, Type: New Feature
