### ISSUE TITLE
Scoped tokens: Does not seems to work like shown in the doc

### ISSUE THREAD

**Issue by Curs3W4ll** [primefaces/primevue#6874] opened 2024-11-26 21:31 UTC
### Describe the bug

I tried using **Scoped Tokens** like shown [in the doc](https://primevue.org/theming/styled/#scopedtokens), but it does not look like it should.  
I'm starting from the Aura preset.

It seems instead being applied only to the component linked with the `:dt` prop, the scoped tokens applies to every component iterations.

After copying the code example from the doc, I get something looking like the following  
![Screenshot 2024-11-26 at 22 32 01](https://github.com/user-attachments/assets/49223dc7-ee23-46ac-9c6b-6a6c51e2d72e)

And here is what was expected (shown in the doc)  
<img width="151" alt="Screenshot 2024-11-26 at 21 33 12" src="https://github.com/user-attachments/assets/0c3cf74c-9dca-45cc-b0d3-4c11bf678c5f">

Tested with Nuxt latest version.  
Also tested with Vue with Vite latest version.

### Reproducer

https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-jk3u2x

### PrimeVue version

4.2.3

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Steps to reproduce the behavior

1. Create a new Nuxt of Vue with Vite blank project
2. Add PrimeVue necessary dependencies
3. Use Aura preset for theme
4. Add Scoped Tokens example [from the doc](https://primevue.org/theming/styled/#scopedtokens) (copy-paste code)
5. See the custom style applied on ToggleSwitch 2 is not Scoped (also applying on ToggleSwitch 1)

### Expected behavior

1. Create a new Nuxt of Vue with Vite blank project
2. Add PrimeVue necessary dependencies
3. Use Aura preset for theme
4. Add Scoped Tokens example [from the doc](https://primevue.org/theming/styled/#scopedtokens) (copy-paste code)
5. ToggleSwitch 1 has the default style (black and white) and ToggleSwitch 2 has a custom style displaying it in amber color

**Comment by tugcekucukoglu** [comment] 2024-11-29 14:30
The demo you've sent seems to be working correctly, so closing.

**Closed by tugcekucukoglu** 2024-11-29 14:30 UTC
Labels: Status: Pending Review

**Comment by Curs3W4ll** [comment] 2024-12-01 12:44
@tugcekucukoglu Still reproducible on my side, maybe it's only on MacOS?  
<img width="130" alt="Screenshot 2024-12-01 at 13 44 25" src="https://github.com/user-attachments/assets/73976e8a-7f12-428a-acfc-df13df897dab">

PS: The issue seems to happen only when removing dependencies (`node_modules/` and `package-lock.json`) and completely reinstalling them

**Comment by pborsutzki** [comment] 2025-01-04 16:11
I am experiencing the exact same issue, but on Window 10 using Firefox. At first I couldn't reproduce it in Chrome. So I started digging a bit:
* It only affects dark mode.
* It only affects dark mode if `darkModeSelector` is set to `system` (default). Forcing dark mode by setting a class on the html element as shown in the docs somehow does not produce the issue (probably that's why the docs render fine).
* The Stackblitz preview for me is always in light mode, but forcing dark mode via the developer tools on the preview does reveal the issue.

So, the [stackblitz reproducer](https://stackblitz.com/edit/primevue-4-ts-vite-issue-template-jk3u2x) of @Curs3W4ll does show the issue for me in both Chrome and in Firefox.
In Chrome, simply right click and inspect the stackblitz preview, then Ctrl+Shift+P and select "Emulate CSS prefers-color-scheme: dark". In Firefox, right click and inspect the preview, then find and press the dark mode button in the styles window.

@tugcekucukoglu please consider having another look into this. Thanks!
