### ISSUE TITLE
Calendar 1st digit swallowed on marked text

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#1765] opened 2021-11-16 13:08 UTC
Bug Report

**Expected Behaviour**
I would expect the calender component to work like the InputText component, when I mark the content and start typing.
In InputText, I can mark the text as on the picture.
![image](https://user-images.githubusercontent.com/8471027/141987089-d7a22b24-81f4-40b2-b588-e91a8def159f.png)
When I now type "12", the textfield displays "12".
I would expect the same behaviour in Calender Component.

**Current behavior**
If I do the same on the Calendar component, the first digit "1" is swallowed and the input only displays "2".

**Minimal reproduction of the problem with instructions**
-Go To Primevue CalendarComponent page https://www.primefaces.org/primevue/showcase/#/calendar
-open the Basic Popup
-select a date
-mark the text with mouse or ctrl+a
-type "12"

**maybe related to Issue #1713**

Vue version: 3.2.20
PrimeVue version: 3.8.2

**Comment by cagataycivici** [comment] 2021-11-17 07:28
Yes, duplicate of 1713.

**Closed by cagataycivici** 2021-11-17 07:28 UTC
