### ISSUE TITLE
optionValue and dataKey combination is broken is Select Components

### ISSUE THREAD

**Issue by fairking** [primefaces/primevue#90] opened 2019-11-20 19:28 UTC
I am trying to bind a single value but looks like it is not working. Could you please look if I my code is correct.
My example:
```
export class DropdownItem {
    id: string;
    name: string;
}
data() {
    return {
        selectedItemId: String,
        dropdownList: DropdownItem[],
    };
},
<Dropdown v-model="selectedItemId" :options="dropdownList" option-value="id" option-label="name" placeholder="Select an Item" />
```
P.S. It would be nice to have some sandbox like https://jsfiddle.net/ so you can check the example.

**Comment by denis-pujdak-adm-it** [comment] 2019-11-22 14:05
Looks like it is working. Closing the issue. Will figure out on my side what is wrong. Sorry for the perturbation.
This is my working jsfiddle https://jsfiddle.net/FairKing/esLawbdq/1/

**Comment by denis-pujdak-adm-it** [comment] 2019-12-10 16:14
Dropdown stops working with the following configuration:
```
<Dropdown v-model="dropdownCity"
    :options="dropdownCities"
    option-label="name"
    option-value="code"
    data-key="code"
    placeholder="Select a City" />
```
![image](https://user-images.githubusercontent.com/13495631/70546967-086aff00-1b68-11ea-8d78-07c8e74c67c9.png)

**Comment by cagataycivici** [comment] 2019-12-20 15:55
Could you please share your code that reproduces the issue?

**Comment by denis-pujdak-adm-it** [comment] 2019-12-20 16:35
The issue happens when both attributes are applied: `option-value` and `data-key`.

**Comment by cagataycivici** [comment] 2019-12-27 06:24
Could you please share sample code that reproduces the issue?

**Comment by denis-pujdak-adm-it** [comment] 2019-12-28 14:40
https://jsfiddle.net/FairKing/esLawbdq/17/

**Comment by cagataycivici** [comment] 2020-01-21 06:54
Also affects multiselect, listbox and selectbutton.

**Closed** 2020-01-21 06:53 UTC
Labels: bug
