### ISSUE TITLE
AccordionHeader: AccordionHeaderContext not available

### ISSUE THREAD

**Issue by alfisdad** [primefaces/primevue#6468] opened 2024-09-24 13:22 UTC
### Describe the bug

According to the documentation, the AccordionHeader component has an interface "AccordionHeaderContext" containing an "active" attribute. I would like to use this in my styling for the Accordion Header, however, the context is always undefined.

I noticed that, in AccordionHeader.d.ts, the DefineComponent and GlobalComponentConstructor declarations are missing the AccordionHeaderContext. Would this be the reason context is undefined?

### Reproducer

https://stackblitz.com/edit/accordionheadercontext?file=src%2FApp.vue

### PrimeVue version

4.0.7

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Attempt to style the AccordionHeader in primevue.ts using the AccortionHeaderContext, e.g.
   ```
import type { AccordionHeaderContext } from 'primevue/accordionheader'

type AccordionHeaderParameters = { context: AccordionHeaderContext }

const design = {
    accordionHeader: (accordionHeaderParameters: AccordionHeaderParameters) => ({
        root: {
            class: [
                'w-full flex items-center cursor-pointer relative no-underline select-none', // Alignments
                'p-2 transition-all duration-200 rounded-t-md', // Padding and transition
                'bg-info text-textOnInfo hover:outline-none hover:ring-info hover:ring-offset-4 hover:ring-1', // Borders and colors
                {
                    'rounded-br-md rounded-bl-md': !accordionHeaderParameters.context.active,
                    'rounded-br-0 rounded-bl-0': accordionHeaderParameters.context.active
                }
            ]
        }
    })
}

export const primeVueOptions: PrimeVueConfiguration = {
    inputStyle: 'filled',
    unstyled: true,
    pt: design
}
```
Results in error: 
`VM5534:1 Global error: TypeError: Cannot read properties of undefined (reading 'active')`

**NOTE**
If you follow the Reproducer StackBlitz link above and check the DevTools Console you'll see the error:

```
primevue.ts:15 Uncaught TypeError: Cannot read properties of undefined (reading 'active')
    at accordionHeader (primevue.ts:15:48)
    at resolve (chunk-BS4QZK3P.js?v=8fa061e2:720:28)
    at getKeyValue (chunk-BS4QZK3P.js?v=8fa061e2:731:45)
    at Proxy._getOptionValue (chunk-LAC6HHWZ.js?v=8fa061e2:320:14)
    at chunk-LAC6HHWZ.js?v=8fa061e2:449:23
    at getValue2 (chunk-LAC6HHWZ.js?v=8fa061e2:369:40)
    at Proxy._getPT (chunk-LAC6HHWZ.js?v=8fa061e2:378:11)
    at Proxy.defaultPT (chunk-LAC6HHWZ.js?v=8fa061e2:448:19)
    at ReactiveEffect.fn (chunk-2LTNOSJU.js?v=8fa061e2:1238:13)
    at ReactiveEffect.run (chunk-2LTNOSJU.js?v=8fa061e2:435:19)
```

### Expected behavior

No error received and styling applied as expected

**Comment by alfisdad** [comment] 2024-09-25 08:52
I included a reproducer. If you follow the StackBlitz link above and check the DevTools Console you'll see the error:
```
primevue.ts:15 Uncaught TypeError: Cannot read properties of undefined (reading 'active')
    at accordionHeader (primevue.ts:15:48)
    at resolve (chunk-BS4QZK3P.js?v=8fa061e2:720:28)
    at getKeyValue (chunk-BS4QZK3P.js?v=8fa061e2:731:45)
    at Proxy._getOptionValue (chunk-LAC6HHWZ.js?v=8fa061e2:320:14)
    at chunk-LAC6HHWZ.js?v=8fa061e2:449:23
    at getValue2 (chunk-LAC6HHWZ.js?v=8fa061e2:369:40)
    at Proxy._getPT (chunk-LAC6HHWZ.js?v=8fa061e2:378:11)
    at Proxy.defaultPT (chunk-LAC6HHWZ.js?v=8fa061e2:448:19)
    at ReactiveEffect.fn (chunk-2LTNOSJU.js?v=8fa061e2:1238:13)
    at ReactiveEffect.run (chunk-2LTNOSJU.js?v=8fa061e2:435:19)
```

**Comment by alfisdad** [comment] 2024-10-02 07:50
Just responding to make sure this issue doesn't get closed due to inactivity. I've checked the reproducer link again just now and confirm the error appears in the DevTools console as per my previous comment. 

BTW Thanks for such a great UI component library!!

**Comment by KumJungMin** [comment] 2024-10-08 11:50
It seems that this issue does not occur in version 4.1.0

**Comment by CCodam** [comment] 2024-10-13 09:34
Place it on the elements instead, in this case the root element.
```ts
const design = {
  accordionHeader: {
    root: (accordionHeaderParameters: AccordionHeaderParameters) => ({
      class: [
        'w-full flex items-center cursor-pointer relative no-underline select-none',
        'p-2 transition-all rounded-t-md',
        'bg-blue text-textOnInfo hover:outline-none hover:ring-blue hover:ring-offset-4 hover:ring-1',
        {
          'rounded-br-md rounded-bl-md':
            !accordionHeaderParameters.context.active,
          'rounded-br-0 rounded-bl-0': accordionHeaderParameters.context.active,
        },
      ],
    }),
  },
};
```

**Comment by alfisdad** [comment] 2024-10-21 14:16
> Place it on the elements instead, in this case the root element.
> 
> ```ts
> const design = {
>   accordionHeader: {
>     root: (accordionHeaderParameters: AccordionHeaderParameters) => ({
>       class: [
>         'w-full flex items-center cursor-pointer relative no-underline select-none',
>         'p-2 transition-all rounded-t-md',
>         'bg-blue text-textOnInfo hover:outline-none hover:ring-blue hover:ring-offset-4 hover:ring-1',
>         {
>           'rounded-br-md rounded-bl-md':
>             !accordionHeaderParameters.context.active,
>           'rounded-br-0 rounded-bl-0': accordionHeaderParameters.context.active,
>         },
>       ],
>     }),
>   },
> };
> ```

That's fixed it. Thank you very much for taking the time.

**Comment by tugcekucukoglu** [comment] 2024-12-11 08:42
If the problem is solved we can close it.

**Closed by tugcekucukoglu** 2024-12-11 08:42 UTC
Labels: Type: Bug
