### ISSUE TITLE
Datatable: Reorder

### ISSUE THREAD

**Issue by emil-1996** [primefaces/primevue#6428] opened 2024-09-18 12:24 UTC
### Describe the bug

Hi PrimeVue team,

I'm encountering an issue with row reordering in the DataTable component. Specifically, I'm unable to reorder rows all the way to the last position in the table.

![image](https://github.com/user-attachments/assets/69af2e13-88ac-43d0-a3d0-bbcdc876a698)

### Reproducer

https://primevue.org/datatable/#reorder

### PrimeVue version

4.0.7

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

ALL

### Steps to reproduce the behavior

 Here’s a breakdown of the issue:

Steps to Reproduce:

Go to the PrimeVue DataTable component with row reordering enabled. (Example: [PrimeVue DataTable](https://primevue.org/datatable/#reorder))
Attempt to move any row to the last position in the table.

### Expected behavior

Actual Behavior: The row cannot be moved to the last position. It seems to stop just before the last element, making it impossible to place it at the bottom of the table.

Expected Behavior: The row should move to the very last position without any issues.

**Comment by philipstarkey** [comment] 2024-09-23 04:10
This looks to be a duplicate of #6014. I also encountered this last week and have raised a PR to fix it in #6424

**Comment by tugcekucukoglu** [comment] 2024-09-25 08:18
Duplicate #6014

**Closed by tugcekucukoglu** 2024-09-25 08:18 UTC
Labels: Status: Needs Triage
