### ISSUE TITLE
DataTable: reorder with drag and drop not working as expected

### ISSUE THREAD

**Issue by Huc91** [primefaces/primevue#6014] opened 2024-07-05 07:49 UTC
### Describe the bug

The bug is visible even in your docs: https://primevue.org/datatable/#reorder.
When I try to drag a row that is not the last to be the last, I'm unable to do it. It can only be second to last.

### Reproducer

I have a video

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 126

### Steps to reproduce the behavior

1. Have DataTable with some rows and the reorder, like in the docs: https://primevue.org/datatable/#reorder.
2. Choose a row to drag to reorder that is not the last one.
3. Try to make it become the last one by dragging it at the bottom
4. You are unable to do it. It can only become second to last.

https://github.com/primefaces/primevue/assets/17967150/330cfeee-c42d-4643-ac45-af1e56f93459

### Expected behavior

Able to reorder all the rows, and be able to put a row as lat

**Comment by Huc91** [comment] 2024-09-03 08:02
Any news on this? I checked v4 of PrimeVue and it's still present.

**Comment by philipstarkey** [comment] 2024-09-24 11:53
I've put in a PR for the fix for this (#6424). The issue is actually dependent on scroll position, as the scroll height is being double counted.

A reproduction is available here: https://stackblitz.com/edit/81ag1m?file=src%2FApp.vue

The first table at the top of the page allows you to drop at the end of the list.
The second table at the bottom of the page (once you scroll down) does not allow you to drop at the end of the list.

**Closed** 2024-09-24 12:52 UTC
Labels: Type: Bug, vue3-portable
