### ISSUE TITLE
DataTable/Column: TypeError: Cannot read properties of null (reading 'sortable')

### ISSUE THREAD

**Issue by cwdx** [primefaces/primevue#5129] opened 2024-01-23 12:20 UTC
### Describe the bug

Error:
```TypeError: Cannot read properties of null (reading 'sortable')```

Version **`3.46.0`
<img width="257" alt="Screenshot 2024-01-23 at 20 15 11" src="https://github.com/primefaces/primevue/assets/6141096/536d8869-5da6-4d1e-990d-75cb56d0d965">

When I add the attribute `:sortable="false"` to the `Column` component the error disappears.

**Stack:**

```
Cannot read properties of null (reading 'sortable')
    at Proxy.getColumnPT8 (primevue_datatable.js?v=f0772dc6:4501:39)
    at Proxy.render$2 (primevue_datatable.js?v=f0772dc6:4757:51)
    at renderComponentRoot (chunk-M7EYYXUF.js?v=f0772dc6:2466:17)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-M7EYYXUF.js?v=f0772dc6:6823:46)
    at ReactiveEffect.run (chunk-M7EYYXUF.js?v=f0772dc6:1401:23)
    at instance.update (chunk-M7EYYXUF.js?v=f0772dc6:6954:17)
    at setupRenderEffect (chunk-M7EYYXUF.js?v=f0772dc6:6964:5)
    at mountComponent (chunk-M7EYYXUF.js?v=f0772dc6:6732:7)
    at processComponent (chunk-M7EYYXUF.js?v=f0772dc6:6686:9)
    at patch (chunk-M7EYYXUF.js?v=f0772dc6:6154:11)
```

**It seems to be an issue with this part of the code:**

```js
// line 4501 @ primevue_datatable.js
sortable: this.column.props.sortable === "" || this.column.props.sortable,
```

props is undefined, so a fix would look something like:
```
sortable: !this.column.props || this.column.props.sortable === "" || this.column.props.sortable,
```

### Reproducer

https://google.com

### PrimeVue version

3.46.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by mertsincan** [comment] 2024-01-23 18:09
Duplicate of #5062

**Closed by mertsincan** 2024-01-23 18:09 UTC
Labels: Status: Needs Triage
